name: build-test
  pull_request:
    branches:
    - 'master'
    - 'release-*'
    - 'dev'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v2
        with:
          file: unit_tests.dockerfile
          tags: test-image:latest
          push: false
